# Generated by Django 5.1.6 on 2025-02-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_count',
        ),
    ]
